# SPDX-FileCopyrightText: LXCat team
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: lxcat

services:
  database:
    image: arangodb:3.12.7.2
    env_file: .env.production
    restart: unless-stopped
    ports:
      - "127.0.0.1:8529:8529"
    volumes:
      - db-data:/var/lib/arangodb3
  app:
    image: ghcr.io/lxcat-project/app:latest
    env_file: .env.production
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - database
    environment:
      ARANGO_URL: http://database:8529
    restart: unless-stopped
  admin-cli:
    image: ghcr.io/lxcat-project/admin-cli:latest
    command: []
    env_file: .env.production
    volumes:
      - ./packages/database/seeds:/packages/database/seeds
    depends_on:
      - database
    environment:
      ARANGO_URL: http://database:8529
volumes:
  db-data:
