name: CI/CD pipeline for LXCat
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/packages/schema/dist
          ${{ github.workspace }}/packages/database/dist
          ${{ github.workspace }}/packages/converter/dist
          ${{ github.workspace }}/app/.next/
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: pnpm install
    - name: Build packages
      run: pnpm build
    - name: Cleanup
      run: rm -rf .next/cache
    - name: Lint
      run: pnpm lint

  test-database:
    needs: build
    runs-on: ubuntu-20.04
    services:
      dind:
        image: docker:24.0.2-dind
        options: --tls=false
    env:
      DOCKER_HOST: "tcp://docker:2375"
      DOCKER_TLS_CERTDIR: ""
      DOCKER_DRIVER: overlay2
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Test @lxcat/database
      run: pnpm -C packages/database test -- run --coverage --reporter=default --reporter=junit --outputFile.junit=./junit.xml --no-threads
